# Setup
title:        K-QuAD
tagline:      Korean Question Answering Dataset
baseurl:      https://github.com/Di-lab-Yonsei/K-QuAD 
paginate:     1

# About/contact
author:
  name:       e05087
  url:        https://github.com/Di-lab-Yonsei/K-QuAD 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
